title: Snoopymeow's blog
# logo: "/assets/images/dog_and_bird.png"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

color_scheme: dark

url: https://snoopy3921.github.io

aux_links:
  "Github": "https://github.com/snoopy3921"
  "Youtube": "https://www.youtube.com/@Snoopymeow"

nav_enabled: true

# Define Jekyll collections
collections:
  luckfox_ldd:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    luckfox_ldd:
      name: 