title: Snoopymeow's blog
# logo: "/assets/images/dog_and_bird.png"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://snoopy3921.github.io

aux_links:
  "Github": "https://github.com/snoopy3921"
  "Youtube": "https://www.youtube.com/@Snoopymeow"



# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  tests:
    permalink: "/_luckfox_ldd/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    tests:
      # Give the collection a name
      name: Tests