title: Ki's Embed Diary
# logo: "/assets/images/dog_and_bird.png"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

color_scheme: light

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/dog_and_bird.ico"

url: https://snoopy3921.github.io

aux_links:
  "Github": "https://github.com/snoopy3921"

nav_enabled: true

# Define Jekyll collections
collections:
  luckfox_ldd:
    permalink: "/:collection/:path/"
    output: true
  100_years_of_solitude:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    luckfox_ldd:
      name: 
    100_years_of_solitude:
      name:
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true


callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow